kind: Service
apiVersion: v1
metadata:
  name: nnchien-practices
  namespace: default
spec:
  selector:
    app: nnchien-practices
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer