apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-11-29T08:57:59Z
  labels:
    run: nnchien-practices
  name: nnchien-practices
  namespace: default
  resourceVersion: "2128"
  selfLink: /api/v1/namespaces/default/services/nnchien-practices
  uid: debae627-f3b4-11e8-bc07-42010a940053
spec:
  clusterIP: 10.3.245.106
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31508
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: nnchien-practices
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.198.200.93
