apiVersion: v1
kind: Service
spec:
  clusterIP: 10.3.245.106
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31508
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: nnchien-practices
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.198.200.93
