---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "go-practices"
  namespace: "default"
  labels:
    app: "go-practices"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "go-practices"
  template:
    metadata:
      labels:
        app: "go-practices"
    spec:
      containers:
      - name: "go-practices"
        image: "gcr.io/nnchien-practices/go-practices:latest"
      ports:
      - containerPort: 8080
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "go-practices-hpa"
  namespace: "default"
  labels:
    app: "go-practices"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "go-practices"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
